### ISSUE TITLE
Unclear usage

### ISSUE THREAD

**Issue by hoanhan101** [nideshchitrakar/PersonalTools#1]
From the documentation
> Scans through a CSV file of addresses to check their validity against the USPS address database. Returns two files - one for correct addresses, and the other for invalid addresses.

I find it hard to understand how it use it. 
- What do I need to run the program?
- What is an example of a CSV file look like?
- What are the format of two returning files?

Instead of contacting nideshchitrakar@bennington.edu for more information, is it easier just to put a nice documentation here?

**Comment by nideshchitrakar** [comment]
https://github.com/IndianaCHE/USPS-Address-Verifier

This is the implementation of the project. I am yet to build a project for linux. This was just a prototype for testing the API.
